version: '3'
services:
  storage:
    image: "arafato/azurite:latest"
    ports:
     - "9569:10000"
     - "9570:10001"
     - "9571:10002"
  functions:
    build: ./example/azure-functions/function-sample
    image: "azure-functions-image"
    ports:
     - "9574:80"
  api-app:
    build: ./src/services/azure-api-app-service/Image/ContactList
    image: "azure-api-app-image"
    ports: 
     - "9567:9000"
     
  # Uncomment if your using windows OS 
  # cosmosdb:
  #   image: "azure-cosmosdb-image"
  #   ports:
  #     - "9500:8081"
  #     - "9502:10250"
  #     - "9503:10251"
  #     - "9504:10252"
  #     - "9505:10253"n
  #     - "9506:10254"