version: '3'
services:
  storage:
    image: "arafato/azurite:latest"
    ports:
     - "9569:10000"
     - "9570:10001"
     - "9571:10002"
  functions:
    image: "azurefunctiondemo"
    ports:
     - "9574:80"
  # cosmosdb:
  #   image: "azure-cosmosdb"
  #   ports:
  #     - "9500:8081"
  #     - "9502:10250"
  #     - "9503:10251"
  #     - "9504:10252"
  #     - "9505:10253"
  #     - "9506:10254"